export const blackjack_21Manifest = {
  slug: 'blackjack-21',
  title: 'Blackjack 21',
  tagline: 'High-octane arcade action.',
  description: 'Master the mechanics and beat your record in Blackjack 21.',
  status: 'playable' as const,
  accent: 'orange' as const,
  tags: ['arcade', 'retro', 'action'],
  cover: '/assets/cover.jpg',
  banner: '/assets/banner.jpg',
  aspect: 3 / 4,
  scoreLabel: 'Score',
  bonusLabel: 'Candy',
  primaryLabel: 'Play',
  scoringNote: 'Survive and score points across waves.',
  startLine: 'Press Space or Click to begin.',
  intro: 'Welcome to Blackjack 21. Ready your reflexes.',
  pauseNote: 'Game paused. Take a breath.',
  tip: 'Timing is everything.',
  controls: [
    { input: 'Space / Click', action: 'Trigger Primary Action' },
    { input: 'Esc / P', action: 'Pause' },
  ],
  legend: [
    { swatch: 'blue' as const, text: 'Player' },
    { swatch: 'orange' as const, text: 'Hazards' },
  ],
  year: new Date().getFullYear(),
}
